version: '3.5'
services:
  phone-service:
    container_name: phone-service
    build:
      context: .
      dockerfile: Dockerfile
    image: phone-service:latest
    ports:
      - '8080:8080'
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/phoneDb

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    command: mongod --smallfiles
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"


volumes:
  mongodata: